server:
  port: 8081
spring:
  application:
    name: ingestion-service
  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      group-id: ingestion-service
      auto-offset-reset: latest
platform:
  ingestion:
    workspace-root: /var/tmp/deep-reader/workspace
